/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package icy.GUI;

import icy.BUS.LoaiSP_BUS;
import icy.BUS.SanPham_BUS;
import icy.DTO.LoaiSP_DTO;
import icy.DTO.SanPham_DTO;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class TKSP_GUI extends javax.swing.JFrame {
    public static TKSP_GUI TKSP=new TKSP_GUI();
    static ThongKe_GUI tk=new ThongKe_GUI();
    DefaultTableModel model=new DefaultTableModel();
    SanPham_BUS bus=new SanPham_BUS();
    SanPham_DTO sp=new SanPham_DTO();
    LoaiSP_BUS busLoai=new LoaiSP_BUS();
    /**
     * Creates new form TKSP_GUI
     */
    public TKSP_GUI() {
        initComponents();
        DocDuLieu();
    }
public void DocDuLieu(){
        if (SanPham_BUS.dssp == null) {
            bus.DocSP();
        }
        //cập nhật Jtable
        Vector header = new Vector();
        header.add("Mã SP");//tên cột table
        header.add("Tên SP");
        header.add("Loại SP");
        header.add("Giá bán");
        header.add("Số lượng");
        header.add("Đơn vị tính");
        header.add("Hình ảnh");
        if (model.getRowCount() == 0) {
            model = new DefaultTableModel(header, 0);
        }
        for (SanPham_DTO sp : SanPham_BUS.dssp) {
            //nạp dữ liệu cho mỗi row
            Vector row = new Vector();
            row.add(sp.MaSP);
            row.add(sp.TenSP);
            if (LoaiSP_BUS.dslsp == null) {
                busLoai.DocLSP();
            }
            for(LoaiSP_DTO lsp : LoaiSP_BUS.dslsp){
                if(lsp.MaLoaiSP.equals(sp.MaLoaiSP)){
                    row.add(lsp.TenLoai);
                }
            }
            row.add(sp.GiaBan);
            row.add(sp.SoLuong);
            row.add(sp.DonViTinh);
            row.add(sp.HinhAnhSP);
            model.addRow(row); //thêm row dữ liệu vào model
            tblSanPham.setModel(model);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbelChinhHinh = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbbLoaiSP = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        txtSoDonVi = new javax.swing.JTextField();
        rbtnGam = new javax.swing.JRadioButton();
        rbtnML = new javax.swing.JRadioButton();
        rbtnCai = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Loại SP", "Giá bán", "Số lượng", "Đơn vị tính", "Hình ảnh"
            }
        ));
        tblSanPham.setGridColor(new java.awt.Color(255, 204, 204));
        tblSanPham.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 102));
        jLabel1.setText("Bảng thống kê sản phẩm");

        lbelChinhHinh.setText("     Hình ảnh");

        jLabel2.setText("Mã SP");

        txtMaSP.setEditable(false);

        jLabel3.setText("Tên SP");

        txtTenSP.setEditable(false);

        jLabel4.setText("Loại SP");

        cbbLoaiSP.setBackground(new java.awt.Color(204, 204, 204));
        cbbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chăm sóc da", "Mỹ phẩm chức năng", "Chống nắng", "Làm sạch da", "Trang điểm", "Chưa phân loại" }));

        jLabel5.setText("Giá bán");

        jLabel6.setText("Đơn vị");

        txtGiaBan.setEditable(false);

        txtSoDonVi.setEditable(false);

        buttonGroup1.add(rbtnGam);
        rbtnGam.setText("gam");

        buttonGroup1.add(rbtnML);
        rbtnML.setText("ml");

        buttonGroup1.add(rbtnCai);
        rbtnCai.setText("Cái");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Trở về");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbelChinhHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenSP)
                                    .addComponent(txtMaSP)
                                    .addComponent(cbbLoaiSP, 0, 168, Short.MAX_VALUE)
                                    .addComponent(txtGiaBan)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnCai)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtnGam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtnML)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbelChinhHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSoDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnGam)
                            .addComponent(rbtnML))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnCai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        int  i=tblSanPham.getSelectedRow();
        if(i>=0){
            sp=bus.dssp.get(i); 
            //hiện ở sản phẩm
            txtMaSP.setText(sp.MaSP);
            txtTenSP.setText(sp.TenSP);
            for(LoaiSP_DTO lsp :busLoai.dslsp){
                if(sp.MaLoaiSP.equals(lsp.MaLoaiSP)){
                    cbbLoaiSP.setSelectedItem(lsp.TenLoai);
                }
            }
            txtGiaBan.setText(sp.GiaBan);
            //gán địa chỉ ảnh và hiện ảnh khi click
            lbelChinhHinh.setIcon(bus.ResizeImage(String.valueOf(sp.HinhAnhSP), lbelChinhHinh));
            // contains giúp tìm chuỗi con có trong chuỗi s
            //replace giúp thay thế ký tự trong chuỗi s
            String s=sp.DonViTinh;
            if(s.contains("gam")==true){
                rbtnGam.setSelected(true);
                txtSoDonVi.setText(s.replace(" gam",""));
            }else if(s.contains("ml")==true){
                rbtnML.setSelected(true);
                txtSoDonVi.setText(s.replace(" ml",""));
            }else{
                rbtnCai.setSelected(true);
                txtSoDonVi.setText(s.replace(" cái",""));
            }
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TKSP.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TKSP_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TKSP_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TKSP_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TKSP_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TKSP.setVisible(true);
                TKSP.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbLoaiSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbelChinhHinh;
    private javax.swing.JRadioButton rbtnCai;
    private javax.swing.JRadioButton rbtnGam;
    private javax.swing.JRadioButton rbtnML;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoDonVi;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
